name: Auto merge main into develop

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOWNSTREAM_MERGE_SECRET }}
      
      - name: Configure git
        run: |
          git config --global user.name "GoatITMediaMachineUser"
          git config --global user.email "thomas+github-machine@goatitmedia.nl"
      
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
     
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Clean workspace
        run: |
          # Remove all untracked files and directories
          git clean -fdx
          # Reset any local changes
          git reset --hard

      - name: Merge main into develop
        id: merge
        run: |
          git merge --no-ff origin/main --strategy=ort --allow-unrelated-histories -m "Merge branch 'main' into 'develop'" || { echo "Merge conflict detected"; git status; git diff; exit 1; }

      - name: Push changes to develop
        run: git push origin develop --admin
