name: Downstream merge master PR

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DOWNSTREAM_MERGE_SECRET }}
      - name: Merge develop into main
        run: |
          git checkout main
          git pull
          git merge origin/develop
          git push
